// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adziwzwactdrgsslnyou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkeml3endhY3Rkcmdzc2xueW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzkxNDUsImV4cCI6MjA2MTQxNTE0NX0.v1emQAcpukL5F1o1rX7hCwNxPSeFXMl02M-Pu4qlGXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);